In [10]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from utils import *

########################################################################
# pathImage = "sudoku.jpeg"
pathImage = "crossword-2.png"
heightImg = 1000
widthImg = 1000
########################################################################

#### 1. PREPARE THE IMAGE
img = cv2.imread(pathImage)
img = cv2.resize(img, (widthImg, heightImg))  # RESIZE IMAGE TO MAKE IT A SQUARE IMAGE
imgBlank = np.zeros((heightImg, widthImg, 3), np.uint8)  # CREATE A BLANK IMAGE FOR TESTING DEBUGGING IF REQUIRED
imgThreshold = preProcess(img)

#### 2. FIND ALL CONTOURS
imgContours = img.copy() # COPY IMAGE FOR DISPLAY PURPOSES
imgBigContour = img.copy() # COPY IMAGE FOR DISPLAY PURPOSES
(cnts, _) = cv2.findContours(imgThreshold, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE) # FIND ALL CONTOURS
cv2.drawContours(imgContours, cnts, -1, (0, 255, 0), 3) # DRAW ALL DETECTED CONTOURS

#### 3. FIND THE BIGGEST CONTOUR AND USE IT AS SUDOKU
biggest, maxArea = biggestContour(cnts) # FIND THE BIGGEST CONTOUR
print(biggest)
if biggest.size != 0:
    biggest = reorder(biggest)
    print(biggest)
    cv2.drawContours(imgBigContour, biggest, -1, (0, 0, 255), 25) # DRAW THE BIGGEST CONTOUR
    pts1 = np.float32(biggest) # PREPARE POINTS FOR WARP
    pts2 = np.float32([[0, 0],[widthImg, 0], [0, heightImg],[widthImg, heightImg]]) # PREPARE POINTS FOR WARP
    matrix = cv2.getPerspectiveTransform(pts1, pts2) # GER
    imgWarpColored = cv2.warpPerspective(img, matrix, (widthImg, heightImg))
    imgDetectedDigits = imgBlank.copy()
    imgWarpBW = cv2.cvtColor(imgWarpColored,cv2.COLOR_BGR2GRAY)

    # Image Array for Display
    imageArray = ([img, imgThreshold, imgContours, imgBigContour],
                  [imgWarpColored, imgWarpBW, imgBlank, imgBlank] )
    stackedImage = stackImages(imageArray, 1, 
        [['raw', 'threshold', 'contours', 'big contour'],
        ['warp color', 'warp bw', 'blank', 'blank']])
    cv2.imshow('Stacked Images', stackedImage)    
    
else:
    print("No Sudoku Found")

cv2.waitKey(0)


[[[ 35 119]]

 [[  6 985]]

 [[958 996]]

 [[978 138]]]
[[[ 35 119]]

 [[978 138]]

 [[  6 985]]

 [[958 996]]]


113